#!/usr/bin/perl 

foreach $i ("3.0",3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9,"4.0",4.1,4.2,4.3,4.4,4.5,4.6,4.7,4.8,4.9,"5.0",5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8,5.9,"6.0")
#foreach $i (3.0 )
{
print "$i\n";
   open FILE,"coord$i" or die 'cannot open file ';
   @data = ();
   while (<FILE>){
   chomp;
   push @data,[ split /\s+/ ];
   }
close FILE ;



   open (OUT, ">NEW$i");

   for ($a=0;$a<10 ;$a++){
        
        print OUT "$data[$a][2] $data[$a][1] $data[$a][0] \n";

    } 

  close  OUT;







}


#このプログラムは分子軸をz軸にとっていた座標系をx軸に取り直す作業を行うものである。ファイルへの書き出し。
#変数として用いる5.0は"5.0"としない限り5のままよみとられてしまう。
